---
windows_web:
  hosts:
    vm-winapp-01:
      ansible_host: winapp-poc.eastus.cloudapp.azure.com
      ansible_user: ansible_svc
      ansible_password: "{{ lookup('ansible.builtin.env', 'ANSIBLE_SVC_PASSWORD') }}"
